language: python
python:
  - "3.6"      # current default Python on Travis CI
  # PyPy versions
  - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
#script:
#  - pytest

deploy:
  provider: pypi
  user: "mastrogiovanni"
  password: "pypi-AgEIcHlwaS5vcmcCJDMxMGZlYzgyLTNkYTctNGJkNy05NDYwLTEzMWY0YzA4ZWU2MAACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYg77MIv1SoNzs306Skf_grFlGz-mCF-eexHAvLJiG6YIM"

