language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
  # PyPy versions
  - "pypy"   # currently Python 2.7.13, PyPy 7.1.1
  - "pypy3"  # currently Python 3.6.1,  PyPy 7.1.1-beta0

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
#script:
#  - pytest

deploy:
  provider: pypi
  user: "mastrogiovanni"
  password: "pypi-AgEIcHlwaS5vcmcCJDMxMGZlYzgyLTNkYTctNGJkNy05NDYwLTEzMWY0YzA4ZWU2MAACJXsicGVybWlzc2lvbnMiOiAidXNlciIsICJ2ZXJzaW9uIjogMX0AAAYg77MIv1SoNzs306Skf_grFlGz-mCF-eexHAvLJiG6YIM"

